user = 
{
    username: String,
    name: String,
    email: String,
    password: String,
    photo: File,
    nationality: Nation,
    nation: Nation,
    uf: State,
    city: City,
    cityForeigner: String ,
    cep: String,
    adrressLine1: String,
    addressLine2: String,
    cpf: String,
    documentType: [RG, CNH, IDEstrangeiro, passaporte],
    documentNumber: String,
    documentPhoto1: File,
    documentPhoto2: File,
    birthDate: Date,
    motherName: String,
    fatherName: String,
    occupation: String,
    userCircle,
    contacts: Object, 
}